/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../src/app/myAccount/maui/container/container.component';
import * as i1 from './container.component.ngfactory';
export function ContainerComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.ContainerComponent,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])},isComponent:true,selector:'agl-maui-container',
      exportAs:(null as any),inputs:{hasShadow:'hasShadow'},outputs:{},hostListeners:{},
      hostProperties:{},hostAttributes:{},providers:([] as any[]),viewProviders:([] as any[]),
      queries:([] as any[]),viewQueries:([] as any[]),entryComponents:([] as any[]),
      changeDetection:1,template:{animations:([] as any[]),ngContentSelectors:['*'],
          encapsulation:0},componentViewType:i1.View_ContainerComponent_0,rendererType:i1.RenderType_ContainerComponent,
      componentFactory:i1.ContainerComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9tYXVpL2NvbnRhaW5lci9jb250YWluZXIuY29tcG9uZW50Lm5nc3VtbWFyeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0FHTC5EaWdpdGFsLkFwcHMvc3JjL2FwcC9teUFjY291bnQvbWF1aS9jb250YWluZXIvY29udGFpbmVyLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
