/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../src/app/myAccount/dashboard/offerTile/offerTile.component';
import * as i1 from '../../../../../../src/app/myAccount/services/contract/idecisioningApi.service';
import * as i2 from './offerTile.component.ngfactory';
export function OfferTileComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.OfferTileComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.IDecisioningApiService}}}],
      lifecycleHooks:[0]},isComponent:true,selector:'agl-offer-tile',exportAs:(null as any),
      inputs:{context:'context'},outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},
      providers:([] as any[]),viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:0},componentViewType:i2.View_OfferTileComponent_0,
      rendererType:i2.RenderType_OfferTileComponent,componentFactory:i2.OfferTileComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9kYXNoYm9hcmQvb2ZmZXJUaWxlL29mZmVyVGlsZS5jb21wb25lbnQubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9kYXNoYm9hcmQvb2ZmZXJUaWxlL29mZmVyVGlsZS5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
