/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../../../../../src/app/myAccount/pages/bills/paymentAssistance/plan/confirm/paymentAssistancePlanConfirm.module';
export const PaymentAssistancePlanConfirmModuleNgFactory:i0.NgModuleFactory<i1.PaymentAssistancePlanConfirmModule> = i0.ɵcmf(i1.PaymentAssistancePlanConfirmModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,
          i1.PaymentAssistancePlanConfirmModule,i1.PaymentAssistancePlanConfirmModule,
          ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9wYWdlcy9iaWxscy9wYXltZW50QXNzaXN0YW5jZS9wbGFuL2NvbmZpcm0vcGF5bWVudEFzc2lzdGFuY2VQbGFuQ29uZmlybS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9wYWdlcy9iaWxscy9wYXltZW50QXNzaXN0YW5jZS9wbGFuL2NvbmZpcm0vcGF5bWVudEFzc2lzdGFuY2VQbGFuQ29uZmlybS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
