/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../src/app/shared/component/payment/paymentSuccess.component';
import * as i1 from '../../../../../../src/app/shared/service/now.service';
import * as i2 from '../../../../../../src/app/shared/service/content.service';
import * as i3 from '../../../../../../src/app/shared/service/email.receipt.service';
import * as i4 from '../../../../../../src/app/myAccount/dashboard/dashboard.component';
import * as i5 from '../../../../../../src/app/myAccount/services/account.service';
import * as i6 from '../../../../../../src/app/shared/service/config.service';
import * as i7 from '../../../../../../src/app/myAccount/modal/modal.service';
import * as i8 from '../../../../../../src/app/myAccount/services/event.service';
import * as i9 from '../../../../../../src/app/shared/service/api.service';
import * as i10 from '../../../../../../src/app/shared/messages/alertMessages';
import * as i11 from '../../../../../../src/app/shared/service/dataLayer.service';
import * as i12 from '../../../../../../src/app/myAccount/services/featureFlag.service';
import * as i13 from '../../../../../../src/app/myAccount/services/contract/idecisioning.service';
import * as i14 from './paymentSuccess.component.ngfactory';
export function PaymentSuccessComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.PaymentSuccessComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.Now}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.ContentService}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.EmailReceiptService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i4.DashboardComponent}}},{isAttribute:false,
          isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.IAccountServiceMA}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i6.ConfigService}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i7.ModalService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i8.EventService}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i9.ApiService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i10.AlertMessages}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i11.DataLayerService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i12.FeatureFlagService}}},{isAttribute:false,
          isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i13.IDecisioningService}}}],
      lifecycleHooks:[0,6]},isComponent:true,selector:'agl-payment-success',exportAs:(null as any),
      inputs:{paymentDetails:'paymentDetails'},outputs:{},hostListeners:{},hostProperties:{},
      hostAttributes:{},providers:([] as any[]),viewProviders:([] as any[]),queries:([] as any[]),
      viewQueries:([] as any[]),entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:0},componentViewType:i14.View_PaymentSuccessComponent_0,
      rendererType:i14.RenderType_PaymentSuccessComponent,componentFactory:i14.PaymentSuccessComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL3NoYXJlZC9jb21wb25lbnQvcGF5bWVudC9wYXltZW50U3VjY2Vzcy5jb21wb25lbnQubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL3NoYXJlZC9jb21wb25lbnQvcGF5bWVudC9wYXltZW50U3VjY2Vzcy5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
