export class PaymentContentModel {
    public bonusEnterCustomAmountText: string;
    public bonusEnterStandardTopuptText: string;
    public bonusTextDebit: string;
    public bonusUnavailableContent: string;
    public bonusUnavailableHeading: string;
    public creditCardInformation: string;
    public creditStateProcessPaymentHeader: string;
    public debitStateBonusPendingHeader: string;
    public debitStateBonusPendingMessage: string;
    public emailFieldInvalidError: string;
    public emailReceiptErrorTextBody: string;
    public emailReceiptErrorTextHeader: string;
    public emailReceiptSentTextBody: string;
    public emailReceiptSentTextHeader: string;
    public iframePaymentFailureContentMessage: string;
    public iframePaymentFailureHeaderMessage: string;
    public iframePaymentPageUnavailableContentMessage: string;
    public iframePaymentPageUnavailableHeaderMessage: string;
    public paymentAmountCreditMaxValidationError: string;
    public paymentAmountPaypalMaxValidationError: string;
    public paymentLoadingModalText: string;
    public paypalDescription: string;
    public payPalUnavailableContent: string;
    public payPalUnavailableHeader: string;
    public paypalPaymentLoadingModalText: string = 'You will be redirected to the PayPal website shortly.';
    public paymentAmountMinValidationError: string;
    public prepaidBalanceUnavailableAlertHeading: string;
    public prepaidBalanceUnavailableAlertContent: string;
}
