/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../src/app/myAccount/rewards/rewards-eligibility.module';
import * as i2 from '@angular/http';
import * as i3 from '../../../../../src/app/shared/service/config.service';
import * as i4 from '../../../../../src/app/shared/repository/aglAuthTokenProvider';
import * as i5 from '../../../../../src/app/myAccount/services/featureFlag.service';
import * as i6 from '../../../../../src/app/myAccount/rewards/services/contract/iRewardsApi.service';
import * as i7 from '../../../../../src/app/myAccount/rewards/services/rewardsApi.service';
import * as i8 from '../../../../../src/app/myAccount/rewards/services/contract/iRewardsEligibility.service';
import * as i9 from '../../../../../src/app/myAccount/rewards/services/rewardsEligibility.service';
import * as i10 from '../../../../../src/app/myAccount/rewards/rewards-routing.guard';
import * as i11 from '@angular/router';
export const RewardsEligibilityModuleNgFactory:i0.NgModuleFactory<i1.RewardsEligibilityModule> = i0.ɵcmf(i1.RewardsEligibilityModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.BrowserXhr,i2.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i2.ResponseOptions,
          i2.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i2.XSRFStrategy,i2.ɵb,
          ([] as any[])),i0.ɵmpd(4608,i2.XHRBackend,i2.XHRBackend,[i2.BrowserXhr,i2.ResponseOptions,
          i2.XSRFStrategy]),i0.ɵmpd(4608,i2.RequestOptions,i2.BaseRequestOptions,([] as any[])),
          i0.ɵmpd(5120,i2.Http,i2.ɵc,[i2.XHRBackend,i2.RequestOptions]),i0.ɵmpd(4608,
              i3.ConfigService,i3.ConfigService,([] as any[])),i0.ɵmpd(4608,i4.AglAuthTokenProvider,
              i4.AglAuthTokenProvider,([] as any[])),i0.ɵmpd(4608,i5.FeatureFlagService,
              i5.FeatureFlagService,[i2.Http]),i0.ɵmpd(4608,i6.IRewardsApiService,
              i7.RewardsApiService,[i2.Http,i3.ConfigService,i4.AglAuthTokenProvider]),
          i0.ɵmpd(4608,i8.IRewardsEligibilityService,i9.RewardsEligibilityService,
              [i6.IRewardsApiService,i5.FeatureFlagService]),i0.ɵmpd(4608,i10.RewardsRoutingGuard,
              i10.RewardsRoutingGuard,[i11.Router,i8.IRewardsEligibilityService]),
          i0.ɵmpd(512,i2.HttpModule,i2.HttpModule,([] as any[])),i0.ɵmpd(512,i1.RewardsEligibilityModule,
              i1.RewardsEligibilityModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9yZXdhcmRzL3Jld2FyZHMtZWxpZ2liaWxpdHkubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0FHTC5EaWdpdGFsLkFwcHMvc3JjL2FwcC9teUFjY291bnQvcmV3YXJkcy9yZXdhcmRzLWVsaWdpYmlsaXR5Lm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
