/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../../src/app/myAccount/pages/usage/usageLegalMessage/usageLegalMessage.component';
import * as i1 from './usageLegalMessage.component.ngfactory';
export function UsageLegalMessageComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.UsageLegalMessageComponent,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])},isComponent:true,selector:'agl-usage-legal-message',
      exportAs:(null as any),inputs:{},outputs:{},hostListeners:{},hostProperties:{},
      hostAttributes:{},providers:([] as any[]),viewProviders:([] as any[]),queries:([] as any[]),
      viewQueries:([] as any[]),entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:0},componentViewType:i1.View_UsageLegalMessageComponent_0,
      rendererType:i1.RenderType_UsageLegalMessageComponent,componentFactory:i1.UsageLegalMessageComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9wYWdlcy91c2FnZS91c2FnZUxlZ2FsTWVzc2FnZS91c2FnZUxlZ2FsTWVzc2FnZS5jb21wb25lbnQubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9wYWdlcy91c2FnZS91c2FnZUxlZ2FsTWVzc2FnZS91c2FnZUxlZ2FsTWVzc2FnZS5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
