/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/homeProfile.module';
import * as i2 from './landing/homeProfileLanding.component.ngfactory';
import * as i3 from './yourHome/homeProfileYourHome.component.ngfactory';
import * as i4 from './cooling/homeProfileCooling.component.ngfactory';
import * as i5 from './heating/homeProfileHeating.component.ngfactory';
import * as i6 from './hotWater/homeProfileHotWater.component.ngfactory';
import * as i7 from './cooking/homeProfileCooking.component.ngfactory';
import * as i8 from './fridgesAndFreezers/homeProfileFridgesAndFreezers.component.ngfactory';
import * as i9 from './otherElectricalItems/homeProfileOtherElectricalItems.component.ngfactory';
import * as i10 from './poolAndSpa/homeProfilePoolAndSpa.component.ngfactory';
import * as i11 from './thankYou/homeProfileThankYou.component.ngfactory';
import * as i12 from '@angular/common';
import * as i13 from '@angular/forms';
import * as i14 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/homeProfileNavigation.service';
import * as i15 from '@angular/router';
import * as i16 from '../../../../../../../src/app/myAccount/pipes/nullableNumber.pipe';
import * as i17 from '../../../../../../../src/app/myAccount/pipes/nullableBoolean.pipe';
import * as i18 from '../../../../../../../src/app/myAccount/services/homeProfile/homeProfileApi.service';
import * as i19 from '@angular/http';
import * as i20 from '../../../../../../../src/app/shared/service/config.service';
import * as i21 from '../../../../../../../src/app/shared/repository/aglAuthTokenProvider';
import * as i22 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/homeProfileMapper';
import * as i23 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/homeProfileState.service';
import * as i24 from '../../../../../../../src/app/myAccount/maui/button/button.module';
import * as i25 from '../../../../../../../src/app/myAccount/maui/flashMessage/flashMessage.module';
import * as i26 from '../../../../../../../src/app/shared/loaders/loading.module';
import * as i27 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/landing/homeProfileLanding.module';
import * as i28 from '../../../../../../../src/app/myAccount/maui/heading/heading.module';
import * as i29 from '../../../../../../../src/app/myAccount/maui/segmentedButtons/segmentedButtons.module';
import * as i30 from '../../../../../../../src/app/myAccount/maui/pageProgressBar/pageProgressBar.module';
import * as i31 from '../../../../../../../src/app/myAccount/maui/radioButtonGroup/radioButtonGroup.module';
import * as i32 from '../../../../../../../src/app/myAccount/maui/secondaryNavigation/secondaryNavigation.module';
import * as i33 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/header/homeProfileHeader.module';
import * as i34 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/footer/homeProfileFooter.module';
import * as i35 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/yourHome/homeProfileYourHome.module';
import * as i36 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/cooling/homeProfileCooling.module';
import * as i37 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/heating/homeProfileHeating.module';
import * as i38 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/hotWater/homeProfileHotWater.module';
import * as i39 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/cooking/homeProfileCooking.module';
import * as i40 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/fridgesAndFreezers/homeProfileFridgesAndFreezers.module';
import * as i41 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/otherElectricalItems/homeProfileOtherElectricalItems.module';
import * as i42 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/poolAndSpa/homeProfilePoolAndSpa.module';
import * as i43 from '../../../../../../../src/app/myAccount/maui/confirmationBanner/confirmationBanner.module';
import * as i44 from '../../../../../../../src/app/myAccount/maui/container/container.module';
import * as i45 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/thankYou/homeProfileThankYou.module';
import * as i46 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/landing/homeProfileLanding.component';
import * as i47 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/yourHome/homeProfileYourHome.component';
import * as i48 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/cooling/homeProfileCooling.component';
import * as i49 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/heating/homeProfileHeating.component';
import * as i50 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/hotWater/homeProfileHotWater.component';
import * as i51 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/cooking/homeProfileCooking.component';
import * as i52 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/fridgesAndFreezers/homeProfileFridgesAndFreezers.component';
import * as i53 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/otherElectricalItems/homeProfileOtherElectricalItems.component';
import * as i54 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/poolAndSpa/homeProfilePoolAndSpa.component';
import * as i55 from '../../../../../../../src/app/myAccount/pages/settings/homeProfile/thankYou/homeProfileThankYou.component';
export const HomeProfileModuleNgFactory:i0.NgModuleFactory<i1.HomeProfileModule> = i0.ɵcmf(i1.HomeProfileModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.HomeProfileLandingComponentNgFactory,i3.HomeProfileYourHomeComponentNgFactory,
              i4.HomeProfileCoolingComponentNgFactory,i5.HomeProfileHeatingComponentNgFactory,
              i6.HomeProfileHotWaterComponentNgFactory,i7.HomeProfileCookingComponentNgFactory,
              i8.HomeProfileFridgesAndFreezersComponentNgFactory,i9.HomeProfileOtherElectricalItemsComponentNgFactory,
              i10.HomeProfilePoolAndSpaComponentNgFactory,i11.HomeProfileThankYouComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i12.NgLocalization,
          i12.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i13.ɵi,i13.ɵi,([] as any[])),
          i0.ɵmpd(4608,i14.HomeProfileUrls,i14.HomeProfileUrls,([] as any[])),i0.ɵmpd(4608,
              i14.HomeProfileNavigationService,i14.HomeProfileNavigationService,[i15.Router,
                  i14.HomeProfileUrls]),i0.ɵmpd(4608,i16.NullableNumberPipe,i16.NullableNumberPipe,
              ([] as any[])),i0.ɵmpd(4608,i17.NullableBooleanPipe,i17.NullableBooleanPipe,
              ([] as any[])),i0.ɵmpd(4608,i18.IHomeProfileApi,i18.HomeProfileApiService,
              [i19.Http,i20.ConfigService,i21.AglAuthTokenProvider]),i0.ɵmpd(4608,
              i22.IHomeProfileMapper,i22.HomeProfileMapper,([] as any[])),i0.ɵmpd(4608,
              i23.IHomeProfileStateService,i23.HomeProfileStateService,[i18.IHomeProfileApi,
                  i22.IHomeProfileMapper]),i0.ɵmpd(512,i15.RouterModule,i15.RouterModule,
              [[2,i15.ɵa],[2,i15.Router]]),i0.ɵmpd(512,i12.CommonModule,i12.CommonModule,
              ([] as any[])),i0.ɵmpd(512,i24.MauiButtonModule,i24.MauiButtonModule,
              ([] as any[])),i0.ɵmpd(512,i25.MauiFlashMessageModule,i25.MauiFlashMessageModule,
              ([] as any[])),i0.ɵmpd(512,i26.LoadingModule,i26.LoadingModule,([] as any[])),
          i0.ɵmpd(512,i27.HomeProfileLandingModule,i27.HomeProfileLandingModule,([] as any[])),
          i0.ɵmpd(512,i13.ɵba,i13.ɵba,([] as any[])),i0.ɵmpd(512,i13.FormsModule,i13.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i28.MauiHeadingModule,i28.MauiHeadingModule,
              ([] as any[])),i0.ɵmpd(512,i29.SegmentedButtonsModule,i29.SegmentedButtonsModule,
              ([] as any[])),i0.ɵmpd(512,i30.MauiPageProgressBarModule,i30.MauiPageProgressBarModule,
              ([] as any[])),i0.ɵmpd(512,i31.MauiRadioButtonGroupModule,i31.MauiRadioButtonGroupModule,
              ([] as any[])),i0.ɵmpd(512,i32.MauiSecondaryNavigationModule,i32.MauiSecondaryNavigationModule,
              ([] as any[])),i0.ɵmpd(512,i33.HomeProfileHeaderModule,i33.HomeProfileHeaderModule,
              ([] as any[])),i0.ɵmpd(512,i34.HomeProfileFooterModule,i34.HomeProfileFooterModule,
              ([] as any[])),i0.ɵmpd(512,i35.HomeProfileYourHomeModule,i35.HomeProfileYourHomeModule,
              ([] as any[])),i0.ɵmpd(512,i36.HomeProfileCoolingModule,i36.HomeProfileCoolingModule,
              ([] as any[])),i0.ɵmpd(512,i37.HomeProfileHeatingModule,i37.HomeProfileHeatingModule,
              ([] as any[])),i0.ɵmpd(512,i38.HomeProfileHotWaterModule,i38.HomeProfileHotWaterModule,
              ([] as any[])),i0.ɵmpd(512,i39.HomeProfileCookingModule,i39.HomeProfileCookingModule,
              ([] as any[])),i0.ɵmpd(512,i40.HomeProfileFridgesAndFreezersModule,i40.HomeProfileFridgesAndFreezersModule,
              ([] as any[])),i0.ɵmpd(512,i41.HomeProfileOtherElectricalItemsModule,
              i41.HomeProfileOtherElectricalItemsModule,([] as any[])),i0.ɵmpd(512,
              i42.HomeProfilePoolAndSpaModule,i42.HomeProfilePoolAndSpaModule,([] as any[])),
          i0.ɵmpd(512,i43.MauiConfirmationBannerModule,i43.MauiConfirmationBannerModule,
              ([] as any[])),i0.ɵmpd(512,i44.MauiContainerModule,i44.MauiContainerModule,
              ([] as any[])),i0.ɵmpd(512,i45.HomeProfileThankYouModule,i45.HomeProfileThankYouModule,
              ([] as any[])),i0.ɵmpd(512,i1.HomeProfileModule,i1.HomeProfileModule,
              ([] as any[])),i0.ɵmpd(1024,i15.ROUTES,() => {
            return [[{path:'',component:i46.HomeProfileLandingComponent},{path:'yourHome',
                component:i47.HomeProfileYourHomeComponent},{path:'cooling',component:i48.HomeProfileCoolingComponent},
                {path:'heating',component:i49.HomeProfileHeatingComponent},{path:'hotWater',
                    component:i50.HomeProfileHotWaterComponent},{path:'cooking',component:i51.HomeProfileCookingComponent},
                {path:'fridgesAndFreezers',component:i52.HomeProfileFridgesAndFreezersComponent},
                {path:'otherElectricalItems',component:i53.HomeProfileOtherElectricalItemsComponent},
                {path:'poolAndSpa',component:i54.HomeProfilePoolAndSpaComponent},{path:'thankYou',
                    component:i55.HomeProfileThankYouComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9wYWdlcy9zZXR0aW5ncy9ob21lUHJvZmlsZS9ob21lUHJvZmlsZS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9wYWdlcy9zZXR0aW5ncy9ob21lUHJvZmlsZS9ob21lUHJvZmlsZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
