/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.text-big[_ngcontent-%COMP%]{font-size:18px;line-height:1.25em}.text-big-long[_ngcontent-%COMP%]{font-size:18px;line-height:1.5em}.text-normal[_ngcontent-%COMP%]{font-size:16px;line-height:1.25em}.text-normal-long[_ngcontent-%COMP%]{font-size:16px;line-height:1.5em}.text-small[_ngcontent-%COMP%]{font-size:14px;line-height:1.25em}.text-small-long[_ngcontent-%COMP%]{font-size:14px;line-height:1.5em}.text-smallest[_ngcontent-%COMP%]{font-size:12px;line-height:1.25em}.text-smallest-long[_ngcontent-%COMP%]{font-size:12px;line-height:1.5em}.example[_ngcontent-%COMP%]{margin-bottom:30px;font-size:16px}.example-label[_ngcontent-%COMP%]{display:block;margin-bottom:8px}.example-content[_ngcontent-%COMP%]{display:block}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9tYXVpL3Nob3djYXNlL3Nob3djYXNlRXhhbXBsZVRlbXBsYXRlLmNvbXBvbmVudC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0FHTC5EaWdpdGFsLkFwcHMvc3JjL2FwcC9teUFjY291bnQvbWF1aS9zaG93Y2FzZS9zaG93Y2FzZUV4YW1wbGVUZW1wbGF0ZS5jb21wb25lbnQuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
