/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../../src/app/myAccount/maui/secondaryNavigation/showcase/secondaryNavigation.showcase.component';
import * as i1 from './secondaryNavigation.showcase.component.ngfactory';
export function ShowcaseSecondaryNavigationComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.ShowcaseSecondaryNavigationComponent,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])},isComponent:true,selector:'agl-maui-showcase-secondary-navigation',
      exportAs:(null as any),inputs:{},outputs:{displayUpdated:'displayUpdated',displayBackButtonUpdated:'displayBackButtonUpdated',
          pageNumberVisibilityUpdated:'pageNumberVisibilityUpdated',pageNumberUpdated:'pageNumberUpdated'},
      hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:0},componentViewType:i1.View_ShowcaseSecondaryNavigationComponent_0,
      rendererType:i1.RenderType_ShowcaseSecondaryNavigationComponent,componentFactory:i1.ShowcaseSecondaryNavigationComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9tYXVpL3NlY29uZGFyeU5hdmlnYXRpb24vc2hvd2Nhc2Uvc2Vjb25kYXJ5TmF2aWdhdGlvbi5zaG93Y2FzZS5jb21wb25lbnQubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9tYXVpL3NlY29uZGFyeU5hdmlnYXRpb24vc2hvd2Nhc2Uvc2Vjb25kYXJ5TmF2aWdhdGlvbi5zaG93Y2FzZS5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
