/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../../src/app/myAccount/pages/usage/alreadySmartMeter/alreadySmartMeter.component';
import * as i1 from '@angular/router';
import * as i2 from './alreadySmartMeter.component.ngfactory';
export function AlreadySmartMeterComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.AlreadySmartMeterComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.Router}}}],
      lifecycleHooks:([] as any[])},isComponent:true,selector:'agl-already-smart-meter',
      exportAs:(null as any),inputs:{},outputs:{},hostListeners:{},hostProperties:{},
      hostAttributes:{},providers:([] as any[]),viewProviders:([] as any[]),queries:([] as any[]),
      viewQueries:([] as any[]),entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:0},componentViewType:i2.View_AlreadySmartMeterComponent_0,
      rendererType:i2.RenderType_AlreadySmartMeterComponent,componentFactory:i2.AlreadySmartMeterComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9wYWdlcy91c2FnZS9hbHJlYWR5U21hcnRNZXRlci9hbHJlYWR5U21hcnRNZXRlci5jb21wb25lbnQubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9wYWdlcy91c2FnZS9hbHJlYWR5U21hcnRNZXRlci9hbHJlYWR5U21hcnRNZXRlci5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
