/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../../../src/app/myAccount/pages/bills/billPanel/billSubtext/billSubtext.component';
import * as i1 from '../../../../../../../../src/app/shared/service/now.service';
import * as i2 from '../../../../../../../../src/app/shared/service/redLineApi.service';
import * as i3 from '../../../../../../../../src/app/myAccount/services/featureFlag.service';
import * as i4 from './billSubtext.component.ngfactory';
export function BillSubtextComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.BillSubtextComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.Now}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.RedLineApiService}}},{isAttribute:false,
          isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.FeatureFlagService}}}],
      lifecycleHooks:[0]},isComponent:true,selector:'agl-bill-subtext',exportAs:(null as any),
      inputs:{type:'type',contract:'contract',address:'address',isTextRowTwoOnly:'isTextRowTwoOnly',
          isBsDDLinks:'isBsDDLinks',isHeaderMessageOnly:'isHeaderMessageOnly',isExtendedDueDate:'isExtendedDueDate',
          isDashboard:'isDashboard'},outputs:{},hostListeners:{},hostProperties:{},
      hostAttributes:{},providers:([] as any[]),viewProviders:([] as any[]),queries:([] as any[]),
      viewQueries:([] as any[]),entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:0},componentViewType:i4.View_BillSubtextComponent_0,
      rendererType:i4.RenderType_BillSubtextComponent,componentFactory:i4.BillSubtextComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9wYWdlcy9iaWxscy9iaWxsUGFuZWwvYmlsbFN1YnRleHQvYmlsbFN1YnRleHQuY29tcG9uZW50Lm5nc3VtbWFyeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0FHTC5EaWdpdGFsLkFwcHMvc3JjL2FwcC9teUFjY291bnQvcGFnZXMvYmlsbHMvYmlsbFBhbmVsL2JpbGxTdWJ0ZXh0L2JpbGxTdWJ0ZXh0LmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
