/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.text-big[_ngcontent-%COMP%]{font-size:18px;line-height:1.25em}.text-big-long[_ngcontent-%COMP%]{font-size:18px;line-height:1.5em}.text-normal[_ngcontent-%COMP%]{font-size:16px;line-height:1.25em}.text-normal-long[_ngcontent-%COMP%]{font-size:16px;line-height:1.5em}.text-small[_ngcontent-%COMP%]{font-size:14px;line-height:1.25em}.text-small-long[_ngcontent-%COMP%]{font-size:14px;line-height:1.5em}.text-smallest[_ngcontent-%COMP%]{font-size:12px;line-height:1.25em}.text-smallest-long[_ngcontent-%COMP%]{font-size:12px;line-height:1.5em}.instalment-left-pane__primary-message[_ngcontent-%COMP%]{font-family:"Open Sans",sans-serif;font-size:16px;font-weight:bold;line-height:1.25em;color:#333}@media (max-width: 767px){.instalment-left-pane__primary-message[_ngcontent-%COMP%]{font-size:14px}}.instalment-left-pane__secondary-message[_ngcontent-%COMP%]{font-family:"Open Sans",sans-serif;font-size:14px;line-height:1.25em;color:#333}.instalment-left-pane__message--grey[_ngcontent-%COMP%]{color:#666 !important}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9tYXVpL3Byb2dyZXNzVHJhY2tlci9zaG93Y2FzZS9leGFtcGxlSW5zdGFsbWVudFByb2dyZXNzSXRlbS9pbnN0YWxtZW50TGVmdFBhbmUvaW5zdGFsbWVudExlZnRQYW5lLmNvbXBvbmVudC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0FHTC5EaWdpdGFsLkFwcHMvc3JjL2FwcC9teUFjY291bnQvbWF1aS9wcm9ncmVzc1RyYWNrZXIvc2hvd2Nhc2UvZXhhbXBsZUluc3RhbG1lbnRQcm9ncmVzc0l0ZW0vaW5zdGFsbWVudExlZnRQYW5lL2luc3RhbG1lbnRMZWZ0UGFuZS5jb21wb25lbnQuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
