/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../src/app/shared/component/alert/alert.component';
import * as i1 from '@angular/platform-browser';
import * as i2 from './alert.component.ngfactory';
export function AlertComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.AlertComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.DomSanitizer}}}],
      lifecycleHooks:[0]},isComponent:true,selector:'agl-alert',exportAs:(null as any),
      inputs:{alertType:'alertType',heading:'heading',body:'body',allowAllHtml:'allowAllHtml',
          isDismissible:'isDismissible'},outputs:{closeEvent:'closeEvent'},hostListeners:{},
      hostProperties:{},hostAttributes:{},providers:([] as any[]),viewProviders:([] as any[]),
      queries:([] as any[]),viewQueries:([] as any[]),entryComponents:([] as any[]),
      changeDetection:1,template:{animations:([] as any[]),ngContentSelectors:['*'],
          encapsulation:2},componentViewType:i2.View_AlertComponent_0,rendererType:i2.RenderType_AlertComponent,
      componentFactory:i2.AlertComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL3NoYXJlZC9jb21wb25lbnQvYWxlcnQvYWxlcnQuY29tcG9uZW50Lm5nc3VtbWFyeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0FHTC5EaWdpdGFsLkFwcHMvc3JjL2FwcC9zaGFyZWQvY29tcG9uZW50L2FsZXJ0L2FsZXJ0LmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
