/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/myAccount/featureIntro/featureIntro.module';
import * as i1 from '../../../../../src/app/myAccount/featureIntro/featureIntroModal/featureIntroModal.component';
import * as i2 from './featureIntroModal/featureIntroModal.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/core';
import * as i5 from '@angular/http';
import * as i6 from '../../../../../src/app/shared/service/config.service';
import * as i7 from '../../../../../src/app/myAccount/rewards/rewards-eligibility.module';
import * as i8 from '../../../../../src/app/shared/repository/aglAuthTokenProvider';
import * as i9 from '../../../../../src/app/myAccount/services/featureFlag.service';
import * as i10 from '../../../../../src/app/myAccount/rewards/services/contract/iRewardsApi.service';
import * as i11 from '../../../../../src/app/myAccount/rewards/services/rewardsApi.service';
import * as i12 from '../../../../../src/app/myAccount/rewards/services/contract/iRewardsEligibility.service';
import * as i13 from '../../../../../src/app/myAccount/rewards/services/rewardsEligibility.service';
import * as i14 from '../../../../../src/app/myAccount/rewards/rewards-routing.guard';
import * as i15 from '@angular/router';
import * as i16 from '../../../../../src/app/myAccount/modal/modal.service';
import * as i17 from '../../../../../src/app/myAccount/featureIntro/services/featureIntro.service';
import * as i18 from '../../../../../src/app/myAccount/featureIntro/services/featureIntroApi.service';
import * as i19 from '../../../../../src/app/myAccount/featureIntro/services/featureIntro-analytics';
import * as i20 from '../../../../../src/app/shared/service/dataLayer.service';
import * as i21 from '../../../../../src/app/myAccount/maui/button/button.module';
import * as i22 from '../../../../../src/app/myAccount/featureIntro/featureIntros.component';
import * as i23 from './featureIntroModal/featureIntroModal.component.ngsummary';
import * as i24 from './featureIntros.component.ngsummary';
import * as i25 from './featureIntroDetail/featureIntroDetail.component.ngsummary';
import * as i26 from '../../../../node_modules/@angular/common/common.ngsummary';
import * as i27 from '../../../../node_modules/@angular/http/http.ngsummary';
import * as i28 from '../rewards/rewards-eligibility.module.ngsummary';
import * as i29 from '../maui/button/button.module.ngsummary';
export function FeatureIntroModuleNgSummary():any[] {
  return [{summaryKind:2,type:{reference:i0.FeatureIntroModule,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])},entryComponents:[{componentType:i1.FeatureIntroModalComponent,
      componentFactory:i2.FeatureIntroModalComponentNgFactory}],providers:[{provider:{token:{identifier:{reference:i3.NgLocalization}},
      useClass:{reference:i3.NgLocaleLocalization,diDeps:[{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i4.LOCALE_ID}}}],
          lifecycleHooks:([] as any[])},useValue:(undefined as any),useFactory:(null as any),
      useExisting:(undefined as any),deps:[{isAttribute:false,isHost:false,isSelf:false,
          isSkipSelf:false,isOptional:false,token:{identifier:{reference:i4.LOCALE_ID}}}],
      multi:false},module:{reference:i3.CommonModule,diDeps:([] as any[]),lifecycleHooks:([] as any[])}},
      {provider:{token:{identifier:{reference:i5.Http}},useClass:(null as any),useValue:(undefined as any),
          useFactory:{reference:i5.ɵc,diDeps:[{isAttribute:false,isHost:false,isSelf:false,
              isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.XHRBackend}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i5.RequestOptions}}}]},useExisting:(undefined as any),
          deps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i5.XHRBackend}}},{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.RequestOptions}}}],
          multi:false},module:{reference:i5.HttpModule,diDeps:([] as any[]),lifecycleHooks:([] as any[])}},
      {provider:{token:{identifier:{reference:i5.BrowserXhr,diDeps:([] as any[]),lifecycleHooks:([] as any[])}},
          useClass:{reference:i5.BrowserXhr,diDeps:([] as any[]),lifecycleHooks:([] as any[])},
          useValue:(undefined as any),useFactory:(null as any),useExisting:(undefined as any),
          deps:([] as any[]),multi:false},module:{reference:i5.HttpModule,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i5.RequestOptions}},
          useClass:{reference:i5.BaseRequestOptions,diDeps:([] as any[]),lifecycleHooks:([] as any[])},
          useValue:(undefined as any),useFactory:(null as any),useExisting:(undefined as any),
          deps:([] as any[]),multi:false},module:{reference:i5.HttpModule,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i5.ResponseOptions}},
          useClass:{reference:i5.BaseResponseOptions,diDeps:([] as any[]),lifecycleHooks:([] as any[])},
          useValue:(undefined as any),useFactory:(null as any),useExisting:(undefined as any),
          deps:([] as any[]),multi:false},module:{reference:i5.HttpModule,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i5.XHRBackend,
          diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i5.BrowserXhr}}},{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.ResponseOptions}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i5.XSRFStrategy}}}],lifecycleHooks:([] as any[])}},
          useClass:{reference:i5.XHRBackend,diDeps:[{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.BrowserXhr}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i5.ResponseOptions}}},{isAttribute:false,
                  isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.XSRFStrategy}}}],
              lifecycleHooks:([] as any[])},useValue:(undefined as any),useFactory:(null as any),
          useExisting:(undefined as any),deps:[{isAttribute:false,isHost:false,isSelf:false,
              isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.BrowserXhr}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i5.ResponseOptions}}},{isAttribute:false,
                  isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.XSRFStrategy}}}],
          multi:false},module:{reference:i5.HttpModule,diDeps:([] as any[]),lifecycleHooks:([] as any[])}},
      {provider:{token:{identifier:{reference:i5.XSRFStrategy}},useClass:(null as any),
          useValue:(undefined as any),useFactory:{reference:i5.ɵb,diDeps:([] as any[])},
          useExisting:(undefined as any),deps:([] as any[]),multi:false},module:{reference:i5.HttpModule,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i6.ConfigService,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])}},useClass:{reference:i6.ConfigService,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])},useValue:(undefined as any),
          useFactory:(null as any),useExisting:(undefined as any),deps:([] as any[]),
          multi:false},module:{reference:i7.RewardsEligibilityModule,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i8.AglAuthTokenProvider,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])}},useClass:{reference:i8.AglAuthTokenProvider,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])},useValue:(undefined as any),
          useFactory:(null as any),useExisting:(undefined as any),deps:([] as any[]),
          multi:false},module:{reference:i7.RewardsEligibilityModule,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i9.FeatureFlagService,
          diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i5.Http}}}],lifecycleHooks:([] as any[])}},
          useClass:{reference:i9.FeatureFlagService,diDeps:[{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.Http}}}],
              lifecycleHooks:([] as any[])},useValue:(undefined as any),useFactory:(null as any),
          useExisting:(undefined as any),deps:[{isAttribute:false,isHost:false,isSelf:false,
              isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.Http}}}],
          multi:false},module:{reference:i7.RewardsEligibilityModule,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i10.IRewardsApiService}},
          useClass:{reference:i11.RewardsApiService,diDeps:[{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.Http}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i6.ConfigService}}},{isAttribute:false,
                  isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i8.AglAuthTokenProvider}}}],
              lifecycleHooks:([] as any[])},useValue:(undefined as any),useFactory:(null as any),
          useExisting:(undefined as any),deps:[{isAttribute:false,isHost:false,isSelf:false,
              isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.Http}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i6.ConfigService}}},{isAttribute:false,
                  isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i8.AglAuthTokenProvider}}}],
          multi:false},module:{reference:i7.RewardsEligibilityModule,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i12.IRewardsEligibilityService}},
          useClass:{reference:i13.RewardsEligibilityService,diDeps:[{isAttribute:false,
              isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i10.IRewardsApiService}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i9.FeatureFlagService}}}],lifecycleHooks:([] as any[])},
          useValue:(undefined as any),useFactory:(null as any),useExisting:(undefined as any),
          deps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i10.IRewardsApiService}}},{isAttribute:false,
              isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i9.FeatureFlagService}}}],
          multi:false},module:{reference:i7.RewardsEligibilityModule,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i14.RewardsRoutingGuard,
          diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i15.Router}}},{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i12.IRewardsEligibilityService}}}],
          lifecycleHooks:([] as any[])}},useClass:{reference:i14.RewardsRoutingGuard,
          diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i15.Router}}},{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i12.IRewardsEligibilityService}}}],
          lifecycleHooks:([] as any[])},useValue:(undefined as any),useFactory:(null as any),
          useExisting:(undefined as any),deps:[{isAttribute:false,isHost:false,isSelf:false,
              isSkipSelf:false,isOptional:false,token:{identifier:{reference:i15.Router}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i12.IRewardsEligibilityService}}}],
          multi:false},module:{reference:i7.RewardsEligibilityModule,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i16.ModalService,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])}},useClass:{reference:i16.ModalService,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])},useValue:(undefined as any),
          useFactory:(null as any),useExisting:(undefined as any),deps:([] as any[]),
          multi:false},module:{reference:i0.FeatureIntroModule,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i17.FeatureIntroService,
          diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i18.FeatureIntroApi}}}],lifecycleHooks:([] as any[])}},
          useClass:{reference:i17.FeatureIntroService,diDeps:[{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i18.FeatureIntroApi}}}],
              lifecycleHooks:([] as any[])},useValue:(undefined as any),useFactory:(null as any),
          useExisting:(undefined as any),deps:[{isAttribute:false,isHost:false,isSelf:false,
              isSkipSelf:false,isOptional:false,token:{identifier:{reference:i18.FeatureIntroApi}}}],
          multi:false},module:{reference:i0.FeatureIntroModule,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i18.FeatureIntroApi,
          diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i5.Http}}},{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i6.ConfigService}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i8.AglAuthTokenProvider}}}],lifecycleHooks:([] as any[])}},
          useClass:{reference:i18.FeatureIntroApi,diDeps:[{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.Http}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i6.ConfigService}}},{isAttribute:false,
                  isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i8.AglAuthTokenProvider}}}],
              lifecycleHooks:([] as any[])},useValue:(undefined as any),useFactory:(null as any),
          useExisting:(undefined as any),deps:[{isAttribute:false,isHost:false,isSelf:false,
              isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.Http}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i6.ConfigService}}},{isAttribute:false,
                  isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i8.AglAuthTokenProvider}}}],
          multi:false},module:{reference:i0.FeatureIntroModule,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])}},{provider:{token:{identifier:{reference:i19.FeatureIntroAnalytics,
          diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i20.DataLayerService}}}],lifecycleHooks:([] as any[])}},
          useClass:{reference:i19.FeatureIntroAnalytics,diDeps:[{isAttribute:false,
              isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i20.DataLayerService}}}],
              lifecycleHooks:([] as any[])},useValue:(undefined as any),useFactory:(null as any),
          useExisting:(undefined as any),deps:[{isAttribute:false,isHost:false,isSelf:false,
              isSkipSelf:false,isOptional:false,token:{identifier:{reference:i20.DataLayerService}}}],
          multi:false},module:{reference:i0.FeatureIntroModule,diDeps:([] as any[]),
          lifecycleHooks:([] as any[])}}],modules:[{reference:i3.CommonModule,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])},{reference:i5.HttpModule,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])},{reference:i7.RewardsEligibilityModule,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])},{reference:i21.MauiButtonModule,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])},{reference:i0.FeatureIntroModule,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])}],exportedDirectives:[{reference:i1.FeatureIntroModalComponent},
      {reference:i22.FeatureIntrosComponent}],exportedPipes:([] as any[])},i23.FeatureIntroModalComponentNgSummary,
      i24.FeatureIntrosComponentNgSummary,i25.FeatureIntroDetailComponentNgSummary,
      i26.CommonModuleNgSummary,i27.HttpModuleNgSummary,i28.RewardsEligibilityModuleNgSummary,
      i29.MauiButtonModuleNgSummary,{summaryKind:3,type:{reference:i16.ModalService,
          diDeps:([] as any[]),lifecycleHooks:([] as any[])}},{summaryKind:3,type:{reference:i17.FeatureIntroService,
          diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i18.FeatureIntroApi}}}],lifecycleHooks:([] as any[])}},
      {summaryKind:3,type:{reference:i18.FeatureIntroApi,diDeps:[{isAttribute:false,
          isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.Http}}},
          {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i6.ConfigService}}},{isAttribute:false,
              isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i8.AglAuthTokenProvider}}}],
          lifecycleHooks:([] as any[])}},{summaryKind:3,type:{reference:i19.FeatureIntroAnalytics,
          diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i20.DataLayerService}}}],lifecycleHooks:([] as any[])}}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9mZWF0dXJlSW50cm8vZmVhdHVyZUludHJvLm1vZHVsZS5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9BR0wuRGlnaXRhbC5BcHBzL3NyYy9hcHAvbXlBY2NvdW50L2ZlYXR1cmVJbnRyby9mZWF0dXJlSW50cm8ubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
