/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../src/app/myAccount/settings/accountDetail/accountDetail.component';
import * as i1 from './accountDetail.component.ngfactory';
export function AccountDetailComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.AccountDetailComponent,diDeps:([] as any[]),
      lifecycleHooks:[0]},isComponent:true,selector:'agl-settings-account-detail',
      exportAs:(null as any),inputs:{model:'model'},outputs:{},hostListeners:{},hostProperties:{},
      hostAttributes:{},providers:([] as any[]),viewProviders:([] as any[]),queries:([] as any[]),
      viewQueries:([] as any[]),entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:0},componentViewType:i1.View_AccountDetailComponent_0,
      rendererType:i1.RenderType_AccountDetailComponent,componentFactory:i1.AccountDetailComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9zZXR0aW5ncy9hY2NvdW50RGV0YWlsL2FjY291bnREZXRhaWwuY29tcG9uZW50Lm5nc3VtbWFyeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0FHTC5EaWdpdGFsLkFwcHMvc3JjL2FwcC9teUFjY291bnQvc2V0dGluZ3MvYWNjb3VudERldGFpbC9hY2NvdW50RGV0YWlsLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
