/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.md-svg-black[_ngcontent-%COMP%]   svg[_ngcontent-%COMP%]   path[_ngcontent-%COMP%]{fill:#000000}.md-svg-dark[_ngcontent-%COMP%]   svg[_ngcontent-%COMP%]   path[_ngcontent-%COMP%]{fill:#48515F}.tracker-wrapper[_ngcontent-%COMP%]{background-color:#f5f5f5;position:relative}.tracker-wrapper__bg[_ngcontent-%COMP%]{position:absolute;top:85px;height:100%;width:100%;z-index:0;background-color:#f5f5f5}.tracker-wrapper__bg[_ngcontent-%COMP%]:before{background-color:#001cb0}.tracker-wrapper__bgblock[_ngcontent-%COMP%]{background-color:#001cb0;height:85px;width:100%;position:absolute;top:0}.tracker-wrapper__container[_ngcontent-%COMP%]{max-width:980px;margin:0 auto;position:relative;z-index:1;width:90%}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9vbW10cmFja2VyL2NvbXBvbmVudHMvdHJhY2tlcldyYXBwZXIvdHJhY2tlcldyYXBwZXIuY29tcG9uZW50LnNjc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9vbW10cmFja2VyL2NvbXBvbmVudHMvdHJhY2tlcldyYXBwZXIvdHJhY2tlcldyYXBwZXIuY29tcG9uZW50LnNjc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
