/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './trackerWrapper.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../../../../src/app/myAccount/ommtracker/components/trackerWrapper/trackerWrapper.component';
const styles_TrackerWrapperComponent:any[] = [i0.styles];
export const RenderType_TrackerWrapperComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_TrackerWrapperComponent,data:{}});
export function View_TrackerWrapperComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),10,'div',[['class',
      'tracker-wrapper']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),3,'div',[['class','tracker-wrapper__container']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
      ['\n    '])),i1.ɵncd((null as any),0),(_l()(),i1.ɵted((null as any),['\n  '])),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          0,'div',[['class','tracker-wrapper__bgblock']],[[4,'height',(null as any)]],
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),0,'div',[['class',
          'tracker-wrapper__bg ab ab--top-right']],[[4,'top',(null as any)]],(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          [' \n']))],(null as any),(_ck,_v) => {
    var _co:i2.TrackerWrapperComponent = _v.component;
    const currVal_0:any = _co.topPixelValue;
    _ck(_v,7,0,currVal_0);
    const currVal_1:any = _co.topPixelValue;
    _ck(_v,9,0,currVal_1);
  });
}
export function View_TrackerWrapperComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'agl-omm-tracker-wrapper',
      ([] as any[]),(null as any),(null as any),(null as any),View_TrackerWrapperComponent_0,
      RenderType_TrackerWrapperComponent)),i1.ɵdid(114688,(null as any),0,i2.TrackerWrapperComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const TrackerWrapperComponentNgFactory:i1.ComponentFactory<i2.TrackerWrapperComponent> = i1.ɵccf('agl-omm-tracker-wrapper',
    i2.TrackerWrapperComponent,View_TrackerWrapperComponent_Host_0,{topPixels:'topPixels'},
    {},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9vbW10cmFja2VyL2NvbXBvbmVudHMvdHJhY2tlcldyYXBwZXIvdHJhY2tlcldyYXBwZXIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0FHTC5EaWdpdGFsLkFwcHMvc3JjL2FwcC9teUFjY291bnQvb21tdHJhY2tlci9jb21wb25lbnRzL3RyYWNrZXJXcmFwcGVyL3RyYWNrZXJXcmFwcGVyLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L0FHTC5EaWdpdGFsLkFwcHMvc3JjL2FwcC9teUFjY291bnQvb21tdHJhY2tlci9jb21wb25lbnRzL3RyYWNrZXJXcmFwcGVyL3RyYWNrZXJXcmFwcGVyLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9vbW10cmFja2VyL2NvbXBvbmVudHMvdHJhY2tlcldyYXBwZXIvdHJhY2tlcldyYXBwZXIuY29tcG9uZW50LnRzLlRyYWNrZXJXcmFwcGVyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cInRyYWNrZXItd3JhcHBlclwiPlxyXG4gIDxkaXYgY2xhc3M9XCJ0cmFja2VyLXdyYXBwZXJfX2NvbnRhaW5lclwiPlxyXG4gICAgPG5nLWNvbnRlbnQ+PC9uZy1jb250ZW50PlxyXG4gIDwvZGl2PlxyXG4gIDxkaXYgY2xhc3M9XCJ0cmFja2VyLXdyYXBwZXJfX2JnYmxvY2tcIiBbc3R5bGUuaGVpZ2h0XT1cInRvcFBpeGVsVmFsdWVcIj48L2Rpdj5cclxuICA8ZGl2IGNsYXNzPVwidHJhY2tlci13cmFwcGVyX19iZyBhYiBhYi0tdG9wLXJpZ2h0XCIgW3N0eWxlLnRvcF09XCJ0b3BQaXhlbFZhbHVlXCI+PC9kaXY+IFxyXG48L2Rpdj4iLCI8YWdsLW9tbS10cmFja2VyLXdyYXBwZXI+PC9hZ2wtb21tLXRyYWNrZXItd3JhcHBlcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFBLGdCQUE2Qix5Q0FDM0I7TUFBQTtNQUFBLDBEQUF3QztNQUFBLG9CQUN0QyxrQkFBeUI7TUFDckIseUNBQ047VUFBQTtVQUFBLDBEQUEyRTtVQUFBLFdBQzNFO1VBQUE7VUFBQSw0Q0FBb0Y7VUFBQTs7SUFEOUM7SUFBdEMsV0FBc0MsU0FBdEM7SUFDa0Q7SUFBbEQsV0FBa0QsU0FBbEQ7Ozs7b0JDTEY7TUFBQTt3Q0FBQSxVQUFBO01BQUE7SUFBQTs7Ozs7In0=
