/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.md-svg-black[_ngcontent-%COMP%]   svg[_ngcontent-%COMP%]   path[_ngcontent-%COMP%]{fill:#000000}.md-svg-dark[_ngcontent-%COMP%]   svg[_ngcontent-%COMP%]   path[_ngcontent-%COMP%]{fill:#48515F}.terms-and-conditions[_ngcontent-%COMP%]{font-size:12px;color:#333;font-family:"Open Sans",sans-serif;margin-top:20px}.terms-and-conditions[_ngcontent-%COMP%]   .point-message[_ngcontent-%COMP%]{padding-bottom:15px}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9wYWdlcy9zZXR0aW5ncy9tb250aGx5QmlsbGluZy9jaG9vc2VEYXRlL21vbnRobHlCaWxsaW5nVGVybXNBbmRDb25kaXRpb25zL21vbnRobHlCaWxsaW5nVGVybXNBbmRDb25kaXRpb25zLmNvbXBvbmVudC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0FHTC5EaWdpdGFsLkFwcHMvc3JjL2FwcC9teUFjY291bnQvcGFnZXMvc2V0dGluZ3MvbW9udGhseUJpbGxpbmcvY2hvb3NlRGF0ZS9tb250aGx5QmlsbGluZ1Rlcm1zQW5kQ29uZGl0aW9ucy9tb250aGx5QmlsbGluZ1Rlcm1zQW5kQ29uZGl0aW9ucy5jb21wb25lbnQuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
