/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../../../../src/app/myAccount/pages/bills/billPanel/billPaymentAmount/billPaymentAmount.component';
import * as i1 from '../../../../../../../../src/app/myAccount/pages/bills/billPanel/billSubtext/billSubtext.component';
import * as i2 from '../../../../../../../../src/app/shared/service/now.service';
import * as i3 from '../../../../../../../../src/app/shared/service/content.service';
import * as i4 from '../../../../../../../../src/app/shared/messages/alertMessages';
import * as i5 from '../../../../../../../../src/app/shared/service/redLineApi.service';
import * as i6 from '../../../../../../../../src/app/myAccount/services/featureFlag.service';
import * as i7 from './billPaymentAmount.component.ngfactory';
export function BillPaymentAmountComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.BillPaymentAmountComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.BillSubtextComponent}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.Now}}},{isAttribute:false,isHost:false,isSelf:false,
          isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.ContentService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i4.AlertMessages}}}],lifecycleHooks:[0]},isComponent:true,
      selector:'agl-bill-payment-amount',exportAs:(null as any),inputs:{type:'type',
          contract:'contract',address:'address',isAmountOnly:'isAmountOnly',isDashboard:'isDashboard'},
      outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:[{token:{identifier:{reference:i1.BillSubtextComponent,
          diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i2.Now}}},{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.RedLineApiService}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i6.FeatureFlagService}}}],lifecycleHooks:[0]}},
          useClass:{reference:i1.BillSubtextComponent,diDeps:[{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i2.Now}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i5.RedLineApiService}}},{isAttribute:false,
                  isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i6.FeatureFlagService}}}],
              lifecycleHooks:[0]},useValue:(undefined as any),useFactory:(null as any),
          useExisting:(undefined as any),deps:[{isAttribute:false,isHost:false,isSelf:false,
              isSkipSelf:false,isOptional:false,token:{identifier:{reference:i2.Now}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i5.RedLineApiService}}},{isAttribute:false,
                  isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i6.FeatureFlagService}}}],
          multi:false}],viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:0},componentViewType:i7.View_BillPaymentAmountComponent_0,
      rendererType:i7.RenderType_BillPaymentAmountComponent,componentFactory:i7.BillPaymentAmountComponentNgFactory},
      {summaryKind:3,type:{reference:i1.BillSubtextComponent,diDeps:[{isAttribute:false,
          isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i2.Now}}},
          {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i5.RedLineApiService}}},{isAttribute:false,
              isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i6.FeatureFlagService}}}],
          lifecycleHooks:[0]}}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL215QWNjb3VudC9wYWdlcy9iaWxscy9iaWxsUGFuZWwvYmlsbFBheW1lbnRBbW91bnQvYmlsbFBheW1lbnRBbW91bnQuY29tcG9uZW50Lm5nc3VtbWFyeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0FHTC5EaWdpdGFsLkFwcHMvc3JjL2FwcC9teUFjY291bnQvcGFnZXMvYmlsbHMvYmlsbFBhbmVsL2JpbGxQYXltZW50QW1vdW50L2JpbGxQYXltZW50QW1vdW50LmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
