/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../../../src/app/shared/component/genericError/genericErrorImage/genericErrorImage.module';
import * as i2 from '@angular/cdk/bidi';
import * as i3 from '@angular/platform-browser';
import * as i4 from '@angular/material/icon';
import * as i5 from '@angular/http';
import * as i6 from '@angular/material/core';
export const GenericErrorImageModuleNgFactory:i0.NgModuleFactory<i1.GenericErrorImageModule> = i0.ɵcmf(i1.GenericErrorImageModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(6144,
          i2.DIR_DOCUMENT,(null as any),[i3.DOCUMENT]),i0.ɵmpd(4608,i2.Directionality,
          i2.Directionality,[[2,i2.DIR_DOCUMENT]]),i0.ɵmpd(5120,i4.MdIconRegistry,
          i4.ICON_REGISTRY_PROVIDER_FACTORY,[[3,i4.MdIconRegistry],[2,i5.Http],i3.DomSanitizer]),
          i0.ɵmpd(512,i6.CompatibilityModule,i6.CompatibilityModule,([] as any[])),
          i0.ɵmpd(512,i2.BidiModule,i2.BidiModule,([] as any[])),i0.ɵmpd(256,i6.MATERIAL_SANITY_CHECKS,
              true,([] as any[])),i0.ɵmpd(512,i6.MdCommonModule,i6.MdCommonModule,
              [[2,i3.DOCUMENT],[2,i6.MATERIAL_SANITY_CHECKS]]),i0.ɵmpd(512,i4.MdIconModule,
              i4.MdIconModule,([] as any[])),i0.ɵmpd(512,i1.GenericErrorImageModule,
              i1.GenericErrorImageModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQUdMLkRpZ2l0YWwuQXBwcy9zcmMvYXBwL3NoYXJlZC9jb21wb25lbnQvZ2VuZXJpY0Vycm9yL2dlbmVyaWNFcnJvckltYWdlL2dlbmVyaWNFcnJvckltYWdlLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9BR0wuRGlnaXRhbC5BcHBzL3NyYy9hcHAvc2hhcmVkL2NvbXBvbmVudC9nZW5lcmljRXJyb3IvZ2VuZXJpY0Vycm9ySW1hZ2UvZ2VuZXJpY0Vycm9ySW1hZ2UubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
